#@ load("@ytt:data", "data")

apiVersion: kbld.k14s.io/v1alpha1
kind: Sources
sources:
- image: rp
  path: .

#@ if/end data.values.push_images:
---
apiVersion: kbld.k14s.io/v1alpha1
kind: ImageDestinations
destinations:
- image: rp
  newImage: #@ data.values.image_repo
